server:
  port: 36000

rabbitmq:
  host: localhost
  port: 5630
  username: codelytv
  password: c0d3ly
  virtual-host: /

keycloak:
  auth-server-url: http://localhost:8080
  ssl-required: none #use external in production
  realm: master
  resource: admin-cli
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  credential:
    username: milena
    password: milena
